"""
Django settings for oauth_project project.

Generated by 'django-admin startproject' using Django 4.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-fafoy6-(mcj$j-7^$$c+8erq(usvcqqyv8gy3p(!oy4u$$cg9+'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    '.ngrok-free.app',  # Allow all ngrok domains
]

# CSRF Configuration for ngrok and local development
CSRF_TRUSTED_ORIGINS = [
    'http://localhost:8000',
    'http://127.0.0.1:8000',
    'https://*.ngrok-free.app',  # Allow all ngrok HTTPS domains
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third-party apps
    'oauth2_provider',
    'rest_framework',
    'corsheaders',
    # Local apps
    'api',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # CORS - must be before CommonMiddleware
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'oauth2_provider.middleware.OAuth2TokenMiddleware',  # OAuth2 token middleware
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'oauth_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'oauth_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ============================================================================
# AUTHENTICATION CONFIGURATION
# ============================================================================

AUTHENTICATION_BACKENDS = [
    'oauth2_provider.backends.OAuth2Backend',
    'django.contrib.auth.backends.ModelBackend',  # Keep for admin access
]

LOGIN_URL = '/admin/login/'

# ============================================================================
# DJANGO REST FRAMEWORK CONFIGURATION
# ============================================================================

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'oauth2_provider.contrib.rest_framework.OAuth2Authentication',
        'rest_framework.authentication.SessionAuthentication',  # For browsable API
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
}

# ============================================================================
# OAUTH2 PROVIDER CONFIGURATION WITH OIDC
# ============================================================================

# Load RSA private key for RS256 JWT signing
RSA_PRIVATE_KEY_PATH = os.path.join(BASE_DIR, 'oauth_project', 'keys', 'oidc.key')
with open(RSA_PRIVATE_KEY_PATH, 'r') as key_file:
    OIDC_RSA_PRIVATE_KEY = key_file.read()

OAUTH2_PROVIDER = {
    # Enable OpenID Connect
    'OIDC_ENABLED': True,
    'OIDC_RSA_PRIVATE_KEY': OIDC_RSA_PRIVATE_KEY,
    
    # Custom OIDC validator for Clerk-compatible claims
    'OAUTH2_VALIDATOR_CLASS': 'api.oidc_validators.ClerkOIDCValidator',

    # Token expiration times (in seconds)
    'ACCESS_TOKEN_EXPIRE_SECONDS': 3600,  # 1 hour
    'AUTHORIZATION_CODE_EXPIRE_SECONDS': 60,  # 1 minute
    'REFRESH_TOKEN_EXPIRE_SECONDS': 86400,  # 24 hours
    'ID_TOKEN_EXPIRE_SECONDS': 3600,  # 1 hour

    # Scopes configuration
    'SCOPES': {
        # OpenID Connect scopes
        'openid': 'OpenID Connect scope',
        'profile': 'Access to profile information',
        'email': 'Access to email address',
        'phone': 'Access to phone number',

        # Custom API scopes
        'contracts:read': 'Read access to contracts',
        'contracts:write': 'Write access to contracts',
        'contracts:delete': 'Delete access to contracts',
    },

    'DEFAULT_SCOPES': ['openid', 'profile'],

    # PKCE (Proof Key for Code Exchange) - Optional for public clients
    'PKCE_REQUIRED': False,

    # Refresh token behavior
    'ROTATE_REFRESH_TOKEN': True,
    'REFRESH_TOKEN_GRACE_PERIOD_SECONDS': 120,

    # Request approval prompt
    'REQUEST_APPROVAL_PROMPT': 'auto',  # 'auto' or 'force'

    # Client secret generator
    'CLIENT_SECRET_GENERATOR_LENGTH': 128,

    # Allowed URI schemes
    'ALLOWED_REDIRECT_URI_SCHEMES': ['http', 'https'],
}

# ============================================================================
# CORS CONFIGURATION
# ============================================================================

# Allow CORS for development - adjust for production
CORS_ALLOW_ALL_ORIGINS = True  # For development only

# For production, use:
# CORS_ALLOWED_ORIGINS = [
#     "http://localhost:3000",
#     "https://yourdomain.com",
# ]

CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]
